### ISSUE TITLE
Support translation (form constraint "( mandatory )" .etc)

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smashlibs#2]
Related with the following `smash` side issue/pull request,
- https://github.com/moovida/smash/issues/2
- https://github.com/moovida/smash/pull/108

`smashlibs` side translation support (like form constraint `( mandatory )` => `( 必須 )`) is also preferable.

<img width="350" alt="mandatory_translation" src="https://user-images.githubusercontent.com/629923/111761975-cfc9e180-88e3-11eb-8dc8-9fa782a1e13e.png">

**Comment by moovida** [comment]
Hi @sanak . You mean that you would like to have this translated in the GUI or you would like to be able to use it translated also in the json file? I am not that happy if it is the second case, but we can talk about it.

**Comment by sanak** [comment]
@moovida (CC: @dkastl, @mbasa-georepublic)  
Oh, I meant the first case (translated in the GUI).

I tried to translate it, once, and the following direct modification worked as expected (although it is only for Japanese...).
commit diff: https://github.com/hyakumori/smashlibs/commit/830c5bd5d2a7960f1783df68d8b541230a005dd3
```diff
-   String _description = "mandatory"; //$NON-NLS-1$
+   String _description = "必須"; //$NON-NLS-1$
```

I am not sure the the meaning of `$NON-NLS-n$` comment, but does this relate with `smash` side internationalization topic (https://github.com/moovida/smash/issues/2) ?

**Comment by moovida** [comment]
@sanak , I completely agree with that change then.

PS: the //$NON-NLS-1$ comes from the initial geopaparazzi development. It is what the eclipse IDE uses for strings for which to ignore translation.

**Comment by sanak** [comment]
@moovida (CC: @dkastl, @mbasa-georepublic)
> I completely agree with that change then.

Okay, thanks for confirmation!

> PS: the //$NON-NLS-1$ comes from the initial geopaparazzi development. It is what the eclipse IDE uses for strings for which to ignore translation.

Okay, thanks for information!
I haven't used Eclipse IDE in a few years, but I will try geopaparazzi build/debug when I have time. 😅

**Comment by moovida** [comment]
Closing this as taken care of.
